### ISSUE TITLE
린트 테스트 코드 작성 질문

### ISSUE THREAD

**Issue by jisungbin** [Pluu/LintStudy#1]
안녕하세요 pluu님, 작성해 주시는 블로그 글 잘 보고 있습니다. 매번 양질의 글 감사합니다.

저도 커스텀 린트를 만들어야 할 때가 있어서 pluu님의 LintStudy 저장소를 종종 참고하고 있습니다.
린트의 테스트 코드를 작성하실 때 어떤 방식으로 하시는지 여쭙고 싶은 게 생겨서 질문 올리게 됐습니다.

[`LiveDataObserveNotNullDetectorTest.kt`](https://github.com/Pluu/LintStudy/blob/master/lint/src/test/java/com/pluu/lint/LiveDataObserveNotNullDetectorTest.kt)를 보면 expect 메시지와 quickfix diff를 하드코딩하고 있습니다.

```kotlin
            .expect(
                """
src/SampleActivity.kt:11: Error: LiveData<Nothing>에는 observeNotNull을 사용할 수 없습니다. [LiveDataObserveNotNullDetector]
        sample.observeNotNull(this) {
               ~~~~~~~~~~~~~~
src/SampleActivity.kt:13: Error: LiveData<Nothing>에는 observeNotNull을 사용할 수 없습니다. [LiveDataObserveNotNullDetector]
        sample2.observeNotNull(this) {
                ~~~~~~~~~~~~~~
2 errors, 0 warnings
                """.trimIndent()
            ).expectFixDiffs(
                """
Fix for src/SampleActivity.kt line 11: Use observe function:
@@ -11 +11
-         sample.observeNotNull(this) {
+         sample.observe(this) {
Fix for src/SampleActivity.kt line 13: Use observe function:
@@ -13 +13
-         sample2.observeNotNull(this) {
+         sample2.observe(this) {
            """.trimIndent()
            )
```

이렇게 하드코딩을 하실 때 사용하시는 도구나 팁이 있을까요? 매번 파일 오프셋과 quickfix diff를 직접 계산하여 작성하시는지 궁금합니다.

**Comment by Pluu** [comment]
@jisungbin 의외로 숫자나 이런건 엄청 간단합니다. 테스트 실패하는 테스트를 작성하면, 어떤 문구를 요구하는지 노출하는데 그걸 복붙하면 됩니다. 

https://youtu.be/p8yX5-lPS6o?t=954

**Comment by jisungbin** [comment]
아하 그런 거였군요, 답변 감사합니다.
첨부해 주신 유튜브 영상도 확인해 보겠습니다.
감사합니다.
